# Generated by Django 2.2.3 on 2019-07-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='path',
            new_name='actual',
        ),
    ]
